services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_HEAP_OPTS: "-Djdk.internal.platform.cgroupv2.enable=false"
    networks:
      - kafka-net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s    

  cipher-dispatcher:
    build:
      context: .
      dockerfile: cipher-dispatcher/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-net 

  infinity-interceptor-1:
    build:
      context: .
      dockerfile: infinity-interceptor/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - cipher-dispatcher
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INTERCEPTOR_ID=instance-1
    networks:
      - kafka-net  

  infinity-interceptor-2:
    build:
      context: .
      dockerfile: infinity-interceptor/Dockerfile
    ports:
      - "8082:8081"
    depends_on:
      - kafka
      - cipher-dispatcher
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - INTERCEPTOR_ID=instance-2
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
    